apiVersion: v1
kind: ReplicationController
metadata:
  name: nsx-demo-rc
  labels:
    app: nsx-demo
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nsx-demo
        secgroup: web-tier
    spec:
      containers:
      - name: nsx-demo
        image: yfauser/nsx-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
